[build]
  publish = "/public"
  command = "hugo"

[build.environment]
  HUGO_THEME = "hugo-theme-learn"
  HUGO_THEMESDIR = "themes"
  HUGO_VERSION = "0.72.0"

[context.production.environment]
  HUGO_BASEURL = "/"

[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
  HUGO_ENABLEGITINFO = "true"

[context.branch-deplpy]
  command = "hugo -b $DEPLOY_PRIME_URL"

[context.branch-deploy.environment]
  HUGO_ENABLEGITINFO = "true"
